### ISSUE TITLE
retry in case of errors 

### ISSUE THREAD

**Issue by michabbb** [Sammyjo20/Saloon#10]
first, thank you for this very nice package, I really like the idea and your concept. the very first question that comes into my mind is: how do I implement a "retry x times with x seconds sleep between" with this? would it make sense to implement a interceptor here or is this something that should be implemented outside of this package? thank for your advice 🙏

**Comment by Sammyjo20** [comment]
I found this online which could help, you can pass this middleware straight into the "addHandler" method in Saloon:

https://github.com/caseyamcl/guzzle_retry_middleware

**Comment by michabbb** [comment]
this is amazing, thanks a lot for letting me know 🙏👍💪
