### ISSUE TITLE
Add casting to DTO

### ISSUE THREAD

**Issue by Wulfheart** [Sammyjo20/Saloon#11]
This package looks really nice. 
Currently I am using https://github.com/spatie/data-transfer-object to cast the json response to a class and vice versa. 
Do you know any good way how to integrate libraries like this into the `Request` classes?

**Comment by Sammyjo20** [comment]
Thanks @Wulfheart!

Maybe if Saloon integrated [the macroable trait](https://github.com/spatie/macroable) by Spatie on the Response, you would be able to add your own method within a response interceptor?

**Comment by Sammyjo20** [comment]
I have added the `Macroable` trait to the response so you can easily add your own methods to extend it.

**Comment by Wulfheart** [comment]
Hey,
sorry for my late reply. I don't think that the `Macroable` trait is the right way forward with this issue.
For your consideration:
What about a method in the request like `responseToDto($response)`? I know that it is not in the response itself but way better than a macro in my opinion. However this would require the docblocks to be generic for the correct typehinting in the `$response->toDTO()`.

**Comment by yurirnascimento** [comment]
Olá @Wulfheart,

I also use the Spatie/Data-Transfer-Object package, a way that this can be solved is directly in your DTO, for example:

## The DTO

```
use \Spatie\DataTransferObject\DataTransferObject;\
use \Illuminate\Http\Request;

class TestDTO extends DataTransferObject {

	public string $someValue;

	public static function fromRequest(Request $request){
		return new self([
			"someValue" => $request->input("someValue")
		]);
	}
	
	public static function fromAPIResponse(array $json) : self
	{
		return new self([
			"someValue" => data_get($json, "someValue")
		]);
	}

}
```

## Action that use TestDTO

```
class TestAction {
	
	public function __invoke(TestDTO $testDTO): TestModel
	{
		
		$test = TestModel($testDTO->all());
		$test->save();
		
		return $test;
	}

}
```

## Ways to use

```
// From Saloon Request
$request = new SomeSaloonRequest();
$dto = TestDTO::fromResponse($request->send());

// Or from Controller
public function store(Request $request, TestAction $testAction)
{
	return TestResource::make(
		$testAction(TestDTO::fromRequest($request))
	);
}
```

Using this way, in my opinion, it has a better separation, and the DTO can implement other ways to initialize itself.

Sorry for the offtopic, I just don't think Saloon would need to solve this.

**Comment by Wulfheart** [comment]
Hey @yurirnascimento,

thanks for your thorough overview. 
However, I think, that a resolution to a DTO should still belong to Saloon as it is about integrating an API and if I write an integration for many devs I want to make the response easily accessible for all the other devs that work with that integration and make it as convenient as possible for them to work with it. Therefore the cognitive overhead of thinking about the correct DTO when using it is too much in my opinion.

**Comment by Sammyjo20** [comment]
Hey @Wulfheart 

That sounds interesting - however I’m worried about introducing a new dependency into Saloon. 

I don’t really know much about DTOs. Would I have a Saloon DTO, or should I allow you to pass in your own DTO into Saloon’s request?

Again, this could be a method added to the connector and you will still be able to access it within all requests. 

E.g: $request->sendResponseToDTO($dto)->send()

Then using a response interceptor, you can populate your response interceptor. This can all be defined in your connector so all requests that use the connector would have the method.

**Comment by Wulfheart** [comment]
I think that the ability to transform the response into something else regardless the naming of it should have a more streamlined process than that.
```php
<?php

class CreateForgeServerRequest extends SaloonRequest
{
    //...

    public function boot(): void
    {
        $this->addResponseInterceptor(function (SaloonRequest $request, SaloonResponse $response) {
            $response::macro('myMethod', function ($name) {
                return 'Hello ' . $name;
            });
    
            return $response;
        });
    }
}
```
This is in my opinion pretty much unnecessary boilerplate code.

My main problem is that I'm lacking a clean and concise idea how this could be achieved.
Another idea I had was to allow custom response classes. Something like this:

```php
<?php
class SomeRequest extends SaloonRequest
{
    // ... Some setup things etc. 
   protected $response = SomeResponse::class;
}

class SomeResponse extends SaloonRespone
{
   public function SomeDTO toDTO(){// ...}
}
```

I hope I can open a PR later that day with this functionality.

**Comment by yurirnascimento** [comment]
> I think that the ability to transform the response into something else regardless the naming of it should have a more streamlined process than that.
> 
> ```
> <?php
> 
> class CreateForgeServerRequest extends SaloonRequest
> {
>     //...
> 
>     public function boot(): void
>     {
>         $this->addResponseInterceptor(function (SaloonRequest $request, SaloonResponse $response) {
>             $response::macro('myMethod', function ($name) {
>                 return 'Hello ' . $name;
>             });
>     
>             return $response;
>         });
>     }
> }
> ```
> 
> This is in my opinion pretty much unnecessary boilerplate code.
> 
> My main problem is that I'm lacking a clean and concise idea how this could be achieved. Another idea I had was to allow custom response classes. Something like this:
> 
> ```
> <?php
> class SomeRequest extends SaloonRequest
> {
>     // ... Some setup things etc. 
>    protected $response = SomeResponse::class;
> }
> 
> class SomeResponse extends SaloonRespone
> {
>    public function SomeDTO toDTO(){// ...}
> }
> ```
> 
> I hope I can open a PR later that day with this functionality.

Now, it makes sense to me, I believe you've pointed out a good way to do this now.

**Comment by Wulfheart** [comment]
Do you want to implement it or may I give it a try?

**Comment by yurirnascimento** [comment]
I haven't collaborated with this package yet, but maybe this could be useful for me too, maybe it could take a day or two to be able to me, to create a PR. As I said, I also use the Spatie package, this caught my attention to give an opinion.

**Comment by Sammyjo20** [comment]
I like the idea of customising the response class. This allows you to define a response class once and not have to keep adding handlers. If you are happy to wait a day or two I'm happy to PR this, but if you are I'd like it to be able to

- If you specify a response on the connector, all requests will use that response
- You can specify a custom response in the request which will overwrite the connector
- It must extend a Saloon response

That would be a super powerful addition to Saloon!

**Comment by yurirnascimento** [comment]
Hi @Wulfheart

I hadn't seen that you had already done a PR.
I ended up doing adding the functionality as you did.

@Wulfheart You can ignore it if it is not ok.

**Comment by Wulfheart** [comment]
@yurirnascimento you did more than I did so it’s awesome.

**Comment by iamniels** [comment]
I was just looking for functionality like this and there are already two PR's :+1:

**Comment by Wulfheart** [comment]
What a time to be alive. 😉
