### ISSUE TITLE
Problem with HasFormBody trait

### ISSUE THREAD

**Issue by sojeda** [Sammyjo20/Saloon#180]
Hi! I have a problem with a Request, I am using HasFormBody trait for simulate this, with Laravel HTTP Client works!

```php
    $post = Http::asForm()->post('https://api.service.com/oauth2/token', [
        'grant_type' => 'client_credentials',
        'client_id' => '9bf9f97e-be08-11ed-afa1-0242ac120002',
        'client_secret' => 'xf0f18ae1e45bac5e22246024b90a4af1f403d86202b290aef46dcfa23abe8c',
    ]);

    $token = $post->json('access_token');
```

But when I try with this, the request fails me.

```php
<?php

namespace App\Http\Integrations\Medplum\Requests;

use Saloon\Contracts\Body\HasBody;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Traits\Body\HasFormBody;

class GetAuthToken extends Request implements HasBody
{
    use HasFormBody;
    /**
     * Define the HTTP method
     *
     * @var Method
     */
    protected Method $method = Method::POST;

    /**
     * Define the endpoint for the request
     *
     * @return string
     */
    public function resolveEndpoint(): string
    {
        return '/oauth2/token';
    }

    protected function defaultBody(): array
    {
        return [
            'grant_type' => 'client_credentials',
            'client_id' => '9bf9f97e-be08-11ed-afa1-0242ac120002',
            'client_secret' => 'xf0f18ae1e45bac5e22246024b90a4af1f403d86202b290aef46dcfa23abe8c',
            'redirect_uri' => 'http://localhost:80/api'
        ];
    }
}
```

```php
$authorizeRequest = new GetAuthToken();
$code = $connector->send($authorizeRequest);
```

Anyone with the same error? I don't know if I'm doing something wrong

**Comment by Sammyjo20** [comment]
Hey @sojeda, thanks for the message.

Your request looks fine.

Can you show me your connector, please? Make sure that you're not overwriting the Content-Type to something else as that will overwrite the `application/x-www-form-urlencoded` Content-Type that is added by Guzzle when you use `HasFormBody`

Additionally, are you using Saloon's default sender (GuzzleSender) or are you using the Laravel HTTP Sender (Separate package)

One small thing I did notice however is in the `defaultBody` of your Saloon request you are adding `redirect_uri` where it is't there on the HTTP client example above - could that be the issue?

**Comment by Sammyjo20** [comment]
Please also make sure those API keys are not real API keys or if they are they are rotated 😅

**Comment by sojeda** [comment]
> 

I use Saloon's default sender (GuzzleSender)
Sorry, redirect_uri is not necessary!

But with what you said I already saw the problem, I have defaultHeaders() in the Connector. 

```
    protected function defaultHeaders(): array
    {
        return [
            'Accept' => 'application/json',
            'Content-Type' => 'application/json',
        ];
    }
```

Shouldn't the Request have priority?

**Comment by Sammyjo20** [comment]
Great, glad that could fix the issue - but you're right, the request **should** take priority, the issue here is that the `Body` traits don't add the Content-Type, it's actually Guzzle under the hood that adds the Content-Type.

I will experiment with adding the Content-Types from Saloon which will mean they take priority and your issue shouldn't appear. I'll add that to the list of things to look at over the next few days :) Thank you for bringing this to my attention.

**Comment by sojeda** [comment]
Thanks to you for the the answer and the package!
