### ISSUE TITLE
Dynamic BaseUrl

### ISSUE THREAD

**Issue by cyrodjohn** [Sammyjo20/Saloon#183]
It is possible to have dynamic base url in a connector? 

The base url of the endpoint changes but it uses the same standard so i think Saloon can help me.

Thanks

**Comment by cyrodjohn** [comment]
I can pass via constructor 

Thanks

**Comment by UnbekanntesPferd** [comment]
@cyrodjohn Can you give an example of how to dynamically set this in constructor?

**Comment by mattsims** [comment]
@UnbekanntesPferd Here you go: https://docs.saloon.dev/the-basics/connectors#constructor-arguments

PS. @Sammyjo20 There is a typo on the above example – constructor param is hinted as `int` when it's a `string` :+1:

**Comment by Sammyjo20** [comment]
Thanks @mattsims - all fixed! :)
