### ISSUE TITLE
Authorization base url is not the same with resolveBaseUrl

### ISSUE THREAD

**Issue by jacksontong** [Sammyjo20/Saloon#184]
HubSpot OAuth2 authorization base url is [https://app.hubspot.com](https://app.hubspot.com) while the api base url is [https://api.hubapi.com](https://api.hubapi.com)

I don't see the option to override the base url in [getAuthorizationUrl](https://github.com/Sammyjo20/Saloon/blob/v2/src/Traits/OAuth2/AuthorizationCodeGrant.php#L65)

What I'm doing is using str_replace to overcome this
```html
<a href="{{ str_replace(config('services.hubspot.api_url'), 'https://app.hubspot.com', $authorizeUrl) }}">Login</a>
```

[https://developers.hubspot.com/docs/api/working-with-oauth#initiating-an-integration-with-oauth-2-0](https://developers.hubspot.com/docs/api/working-with-oauth#initiating-an-integration-with-oauth-2-0)

**Comment by juse-less** [comment]
Sorry for the short comment. I'm on my phone, but was hoping the pointer is enough to help. 🙂

The Saloon documentation says this:
https://docs.saloon.dev/digging-deeper/oauth2-authentication#getting-setup
> We recommend that you create a new connector in your integration just for authentication with the third-party provider. This can help keep the authentication and API code separate

**Comment by jacksontong** [comment]
Thanks for quick reply, but in this case it's just the authorization url which has different base url, whilst the access and refresh token base url is still api

https://api.hubapi.com/oauth/v1/access-tokens/

> We recommend that you create a new connector in your integration just for authentication with the third-party provider. This can help keep the authentication and API code separate

With this approach I'll have to create oauth connector just to generate the authorization url, and the api connector still have to implement oauth to exchange the token.

[https://developers.hubspot.com/docs/api/oauth/tokens](https://developers.hubspot.com/docs/api/oauth/tokens)

**Comment by Sammyjo20** [comment]
Hey @jacksontong 

Apologies for the delay on this one! 

Have you tried passing the full URL into your authorization code config?

```php
protected function defaultOauthConfig(): OAuthConfig
{
    return OAuthConfig::make()
	->setAuthorizeEndpoint('https://api.hubapi.com/oauth/v1/access-tokens')
        ->setTokenEndpoint('/oauth/tokens')
}
```

I believe Saloon should recongnise that the endpoint is a full URL and will use that instead of combining the base URL + endpoint.

See the URL helper code which is used by Saloon when building URLs:

https://github.com/Sammyjo20/Saloon/blob/v2/src/Helpers/URLHelper.php#L28

**Comment by jacksontong** [comment]
yep, it works. Thanks for your support.
