### ISSUE TITLE
Is there any way to override the full url of a request in a plugin?

### ISSUE THREAD

**Issue by scajal** [Sammyjo20/Saloon#189]
I'm trying to develop a plugin to proxy a request to a provided URL.

For example, the original request would go to https://abc.xyz/test, and i'd like to proxy-it to https://proxy.me?to=https://abc.xyz/test. 

Is this possible? I don't see any change right now apart from modifying the connector and request urls.

**Comment by scajal** [comment]
If anyone is wondering and needs to do this, i've solved it using reflection. 
Here's an example:

```
trait Proxable
{
    /**
     * Boot the proxable plugin.
     */
    public function bootProxable(PendingRequest $pendingRequest): void
    {
        // Create an reflected instance of the pending request.
        $reflection = new ReflectionClass($pendingRequest);

        // Set the new URL.
        tap($reflection->getProperty('url'))
            ->setAccessible(true)
            ->setValue(
                $pendingRequest, 
                <proxy url>.'?_to='.urlencode($pendingRequest->getUrl())
            );
    }
}
```

**Comment by Sammyjo20** [comment]
Hey @scajal - I have now added two new methods to the PendingRequest instance: `setUrl` and `setMethod` - so feel free to update your reflection code if you want to!

Thank you
