### ISSUE TITLE
Escaped backslashes or unicode in json

### ISSUE THREAD

**Issue by Whizboy-Arnold** [Sammyjo20/Saloon#194]
Could you provide means to give json parameters when building the body. I would like to not escape my urls within the body

View: https://stackoverflow.com/questions/3723243/why-does-json-encoder-adds-escaping-character-when-encoding-urls/4832057#4832057

**Comment by Sammyjo20** [comment]
Sorry I'm a little confused @Whizboy-Arnold - do you mind clarifying a little bit? Thanks!

**Comment by juse-less** [comment]
@Sammyjo20 Hey.

I think what @Whizboy-Arnold means is that he'd like to add/overwrite the JSON flags in the [JsonBodyRepository](https://github.com/Sammyjo20/Saloon/blob/c2e4eeec8a60b39a675c0b8555f3d1d9f21b7a30/src/Repositories/Body/JsonBodyRepository.php).
JSON _should_ be escaped, like PHP does, but isn't required.
AFAIK, most people also don't escape it, unlike PHP.
I've also faced issues with escaped JSON in the past, where APIs don't actually support JSON, even though that's their 'data format'.
So I can relate to the situation.

That being said, you should be able to straight-off snag my 'HasJsonFlags' trait in my private concept repo (src/Concerns/HasJsonFlags), you've been invited to.
Then you should be able to add it to the [JsonBodyRepository](https://github.com/Sammyjo20/Saloon/blob/c2e4eeec8a60b39a675c0b8555f3d1d9f21b7a30/src/Repositories/Body/JsonBodyRepository.php), and change
```php
public function __toString(): string
{
    return json_encode($this->all(), JSON_THROW_ON_ERROR);
}
```

to something like
```php
public function __toString(): string
{
   $json = is_null($this->getJsonFlags())
        ? json_encode($this->all())
        : json_encode($this->all(), $this->getJsonFlags());

    // If JSON_THROW_ON_ERROR is not set, turn `false` into an empty string.
    return $json === false ? '' : $json;
}
```

Or if you want to enforce a JSON Exception, something like:
```php
public function __toString(): string
{
    return json_encode($this->all(), $this->getJsonFlags() | JSON_THROW_ON_ERROR);
}
```

Keep in mind, though, if this is done - using interface type hints will not resolve the new JSON flag methods.

**Comment by Sammyjo20** [comment]
Hey @Whizboy-Arnold really sorry for the delay on this!

I will get a fix out for you soon which will allow you to customise the JSON flags.

**Comment by Whizboy-Arnold** [comment]
Ok thank you for the support

**Comment by Sammyjo20** [comment]
Hey @Whizboy-Arnold I've made a PR (#229) to add support for this. Please could you take a look over it to see if it would be suitable for you?

**Comment by Whizboy-Arnold** [comment]
Hey I also just noticed this is officially supported and documented in version 3, [JSON flags](https://docs.saloon.dev/the-basics/request-body-data/json-body#json-flags) . Thanks a lot for that, good to see the nice things version 3 brings, including the different formats of body, more Laravel support, It is just AWESOME.
