### ISSUE TITLE
Modify response before sending it to the client

### ISSUE THREAD

**Issue by Juuuke** [Sammyjo20/Saloon#204]
Hello,

Is there a way to modify the response before sending it to the client ? I am able to retrieve the response in the middleware using "onResponse()" however I did not find a way to update the content of the body response

Sorry if the question does not belong here

Have a good day!

**Comment by Sammyjo20** [comment]
Hey @Juuuke! 

I believe you'll be able to do this by modifying the underlying stream that Guzzle creates.

What kind of body is it? JSON? Since Guzzle handles Streams behind the scenes you have to build your own. For example if you're using JSON you'll need to use `json_encode`. Guzzle also provides a handy `Utils` class to create a stream from a string.

Try something like this...

```php
$request->middleware()->onResponse(function (Response $response) {
    // Don't use ->json() as that will cache the JSON body
    $data = json_decode($response->body());
    
    $stream = Utils::streamFor(json_encode(array_merge($data, ['something' => 'else'])));

    $response->getPsrResponse()->withBody($stream);

    return $response;
});
```

**Comment by Juuuke** [comment]
Thanks for the hint :) - I have tried that but I don't seem to make it work. The response is still the original one. 

Here's the way I am calling the onResponse() from my connector, (https://docs.saloon.dev/digging-deeper/middleware#using-constructors) maybe this is the problem or I misunderstood something?

```php
public function __construct()
{
    $this->middleware()->onResponse(new SerializeJsonApi);
}
```

(I have tried your code in the SerializeJsonApi class)

Thanks for your time :)

**Comment by Juuuke** [comment]
I tried a lot of things today, I found that the response is indeed updated in the middleware but the output is still the original one outside the middleware. Same goes for headers.

I don't know what else to try, if anyone finds a solution feel free to tag me here :)

**Comment by Sammyjo20** [comment]
Yeah, I noticed this as well when I did some testing last night. 

I'm going to check to see if there's a bug in the middleware pipeline and the new result isn't being passed down the middleware pipeline properly.

**Comment by Juuuke** [comment]
Thanks!

I'll try on my side and submit a PR if I find something.

**Comment by Juuuke** [comment]
@Sammyjo20 I found the "issue", here's the thing :

```php

MiddlewarePipeline.php:100

$callbackWrapper = Closure::bind(function (Response $response) use ($callable): Response {
    $result = $callable($response);

    return $result instanceof Response ? $result : $response;
}, new class {});

```

You're expecting a Http\Saloon\Response in order to return the result of the callback, otherwise you return the original response.

I managed to make it work by returning a Saloon response instead of a Guzzle PSR7 response : 

```php

$pendingRequest = $response->getPendingRequest();
$responseClass = $pendingRequest->getResponseClass();
        
 $stream = Utils::streamFor(json_encode($resources));
 $response = $response->getPsrResponse()->withBody($stream);

return $responseClass::fromPsrResponse($response, $pendingRequest);
````

I don't know if you intended to do it this way, if so, perhaps the doc should be updated ? 

Thanks for your time :)

**Comment by Juuuke** [comment]
@Sammyjo20 Here is the first "issue" : 

```php
saloon/src/Helpers/MiddlewarePipeline.php:100

$callbackWrapper = Closure::bind(function (Response $response) use ($callable): Response {
    $result = $callable($response);

    return $result instanceof Response ? $result : $response;
}, new class {});
```

You're expecting a `\Saloon\Contracts\Response` but you're getting `GuzzleHttp\Psr7\Response` because of me modifying the stream using : 

```php
$response = $response->getPsrResponse()->withBody($stream);
```

Therefore, the original response is returned instead of the result of the callback. I managed to make it work by recreating the Saloon Reponse in my Middleware SerializeJsonApi : 

```php

$pendingRequest = $response->getPendingRequest();
$responseClass = $pendingRequest->getResponseClass();

$stream = Utils::streamFor(json_encode($resources));
$response = $response->getPsrResponse()->withBody($stream);

return $responseClass::fromPsrResponse($response, $pendingRequest);
```

Last issue, the response is not set correctly :

```php

saloon/src/Http/PendingRequest.php:334

public function executeResponsePipeline(ResponseContract $response): ResponseContract
{
    $this->middleware()->executeResponsePipeline($response);

    return $response;
}
```
The original response is returned here, while it should return the response returned from the executeResponsePipeline method instead ! :)

**Comment by Juuuke** [comment]
@Sammyjo20 Sorry I updated my previous answer, I deleted it by mistake. :)

**Comment by Sammyjo20** [comment]
Hey @Juuuke wow nice find! Thank you - I'm happy to PR this, I will make a PR tomorrow for you.

**Comment by Sammyjo20** [comment]
Hey @Juuuke thanks again for finding the bug, if you update Saloon - could you try and again and let me know if it's fixed for you please? Thanks!

**Comment by Juuuke** [comment]
Hey!

Thanks for the update, I will try it this evening as I am not at home right now. I will let you know 🙂

Thanks again!

**Comment by Juuuke** [comment]
@Sammyjo20 All good. Works great. Thank you so much for you time :)
