### ISSUE TITLE
DisablesSSLVerification & Saloon v2

### ISSUE THREAD

**Issue by heikokrebs** [Sammyjo20/Saloon#210]
Is there a way to disable the SSL Verification in v2, as with `DisablesSSLVerification` in v1?

**Comment by Sammyjo20** [comment]
Hey @heikokrebs - yes there is! 

You can use Guzzle's verify option in Saloon config on either your connector or request. 

```php
protected function defaultConfig(): array
{
     return [
          'verify' => false,
     ];
}

// or 

$connector = new Connector;
$connector->config()->add('verify', false);

// or

$request = new Request;
$request->config()->add('verify', false);
```

**Comment by heikokrebs** [comment]
...ok...just found the answer 🙈
i was too fast and dump. Thanks a lot for the fast reply @Sammyjo20 

Keep up the great work!
