### ISSUE TITLE
v1: Malformed json to MockResponse causes exception with from getHeaders()

### ISSUE THREAD

**Issue by GlennBags** [Sammyjo20/Saloon#213]
Reporting this for a possible enhancement, as it took a while to understand the actual issue.

I had a comma on the last property/value of the json sending to MockResponse, such that the json_decode() returned null.
Then using that null return value in MockResponse::make().
When running my test, I got the following:

  The following exception occurred during the last request:

  TypeError: Sammyjo20\Saloon\Http\MockResponse::getHeader(): Return value must be of type string, null returned in /var/www/html/vendor/sammyjo20/saloon/src/Traits/CollectsHeaders.php:104
  Stack trace:
  #0 /var/www/html/vendor/sammyjo20/saloon/src/Http/MockResponse.php(147): Sammyjo20\Saloon\Http\MockResponse->getHeader()
  #1 /var/www/html/vendor/sammyjo20/saloon/src/Http/MockResponse.php(162): Sammyjo20\Saloon\Http\MockResponse->getFormattedData()
  #2 /var/www/html/vendor/sammyjo20/saloon/src/Http/Middleware/MockMiddleware.php(39): Sammyjo20\Saloon\Http\MockResponse->toGuzzleResponse()
  #3 /var/www/html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): Sammyjo20\Saloon\Http\Middleware\MockMiddleware->Sammyjo20\Saloon\Http\Middleware\{closure}()
  #4 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()
  #5 /var/www/html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
  #6 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke()
  #7 /var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
  #8 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke()
  #9 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(107): GuzzleHttp\Client->transfer()
  #10 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->sendAsync()
  #11 /var/www/html/vendor/sammyjo20/saloon/src/Managers/RequestManager.php(217): GuzzleHttp\Client->send()
  #12 /var/www/html/vendor/sammyjo20/saloon/src/Managers/RequestManager.php(199): Sammyjo20\Saloon\Managers\RequestManager->sendSyncRequest()
  #13 /var/www/html/vendor/sammyjo20/saloon/src/Traits/SendsRequests.php(29): Sammyjo20\Saloon\Managers\RequestManager->send()
  #14 /var/www/html/vendor/sammyjo20/saloon/src/Http/SaloonConnector.php(75): Sammyjo20\Saloon\Http\SaloonRequest->send()

I see that MockResponse accepts "mixed" for $data, but perhaps shouldn't be `null`, since it's throwing?

Either way, putting this here in the hopes that better error checking could perhaps have the Mock throw a better message as to the cause.

**Comment by Sammyjo20** [comment]
Many thanks for positing this issue @GlennBags - I have created #231 which should fix the issue.
