### ISSUE TITLE
OAuth2: GetAccessTokenRequest missing code_verifier body field

### ISSUE THREAD

**Issue by relaypilot** [Sammyjo20/Saloon#221]
The [current implementation](https://github.com/Sammyjo20/Saloon/blob/v2/src/Http/OAuth2/GetAccessTokenRequest.php) provides the following body fields to get an access token (OAuth2):

    public function defaultBody(): array
    {
        return [
            'grant_type' => 'authorization_code',
            'code' => $this->code,
            'client_id' => $this->oauthConfig->getClientId(),
            'client_secret' => $this->oauthConfig->getClientSecret(),
            'redirect_uri' => $this->oauthConfig->getRedirectUri(),
        ];
    }

The API I am connecting to requires an extra body field in order to get an access token:
`'code_verifier' => 'XXX',`

I have tried adding the `code_verifier` in the header or in the query (example below), because I didn't find a way to extend the default body fields [in the documentation](https://docs.saloon.dev/digging-deeper/oauth2-authentication/oauth2-authentication#customising-the-requests):

    $authConnector->getAccessToken(
        $request->code,
        $request->state,
        $expectedState,
        false,
        requestModifier: function (Saloon\Contracts\Request $request) use ($codeVerifier) {
            $request->query()->add('code_verifier', $codeVerifier);
        }
    );

The above didn't work because it has to be set in the request body.

Would it be possible to add a new method to add extra fields to the body? 
Something like a `body()` method:

    requestModifier: function (Saloon\Contracts\Request $request) use ($codeVerifier) {
        $request->body()->add('code_verifier', $codeVerifier);
    }

Or maybe make `code_verifier` as an optional field of the `defaultBody()` array? (although I'm not sure if this is a common requirement for OAuth2 APIs)

    public function defaultBody(): array
    {
        return [
            'grant_type' => 'authorization_code',
            'code' => $this->code,
            'code_verifier' => $this->codeVerifier,
            'client_id' => $this->oauthConfig->getClientId(),
            'client_secret' => $this->oauthConfig->getClientSecret(),
            'redirect_uri' => $this->oauthConfig->getRedirectUri(),
        ];
    }

Or please let me know if I missed something - Thank you Sammy for this amazing package ❤️

**Comment by Sammyjo20** [comment]
Hey @relaypilot 

Many thanks for your kind words and for submitting an issue, it helps make Saloon better! I see what you mean, it does make it tricky since the `body()` method is only exposed through the `HasBody` interface. You **should** still be able to do the following, but just change the type-hint from `Saloon\Contracts\Request` to `Saloon\Http\OAuth2\GetClientCredentialsTokenRequest`. Then you should be able to add to the body like you were doing before...

```php
requestModifier: function (GetClientCredentialsTokenRequest $request) use ($codeVerifier) {
    $request->body()->add('code_verifier', $codeVerifier);
}
```

Let me know if this works :)

**Comment by relaypilot** [comment]
Excellent, it works fine with `GetAccessTokenRequest` 🥇
