### ISSUE TITLE
boolean value in query strings sent as binary digits

### ISSUE THREAD

**Issue by harryqt** [Sammyjo20/Saloon#228]
I have an API, which have optional query parameters.

```php
$connector = new FooConnector;

$request = new FooRequest();
$request->query()->add('fixed_value', true); // "false" have same issue 

$response = $connector->send($request);
$response->json();
```

response:

```json
{
    "status": false,
    "statusCode": 400,
    "code": "INVALID_REQUEST_PARAMS",
    "message": "fixed_value must be a boolean"
}
```

But if comment out `query()->add()` method:

```php
//$request->query()->add('fixed_value', true);
```

I get successful response.

## Issue:

Judging by the error response, `fixed_value` query string is not boolean, which is incorrect.

Is there any way I can see what request is actually sent? Like full headers and params?

Note: This works fine when using Guzzle, Postman, cURL etc.

**Comment by harryqt** [comment]
# Update:

I believe I have debugged the culprit. I figured out how to debug.

When using Saloon, if I do:

```php
$request->query()->add('fixed_value', true);
```

Then actual request sent as:

```php
//...
> GET /v1/rate?fixed_rate=1 HTTP/1.1
```

But in standalone Guzzle it sent as:

```php
//...
> GET /v1/rate?fixed_rate=true HTTP/1.1
```

## Problem:
The main issue is that, `boolean` values sent as binary. :(

Any fix?

**Comment by harryqt** [comment]
The main issue is that `http_build_query()` converts `boolean` to `binary` and also omits `null` values. :/

**Comment by harryqt** [comment]
I don't think this needs fixing.

**Comment by Sammyjo20** [comment]
Hey @Dibbyo456 

I agree this is a bit of an annoying issue, in version three I’m going to change it so it can properly convert booleans to their string counterparts like “true” or “false”

Would that be a useful change?

**Comment by harryqt** [comment]
Laravel's [Array::query()](https://laravel.com/docs/10.x/helpers#method-array-query) & [guzzle/psr7](https://github.com/guzzle/psr7/blob/815698d9f11c908bc59471d11f642264b533346a/src/Query.php#LL71C12-L71C12) both have the issues. I guess they're following standards. Maybe you should just leave it this way. 🤔

**Comment by Sammyjo20** [comment]
I do also agree with that. I will leave it for now, thanks @Dibbyo456

**Comment by harryqt** [comment]
For future readers, hook this up in your Connector/Request class. 

```php
public function boot(PendingRequest $pendingRequest): void
{
    $queries = $pendingRequest->query()->all();

    array_walk($queries, function (&$value) {
        if (is_bool($value)) {
            $value = $value ? 'true' : 'false';
        }
    });
    
    $pendingRequest->query()->set($queries);
}
```
