### ISSUE TITLE
Constructor parameter types in request  class not freely choosable

### ISSUE THREAD

**Issue by effem** [Sammyjo20/Saloon#235]
Hi,

for a project of mine i wanted to use saloon for the api communication with twitter.
For this I created a twitter connector according to the documentation looking like this:
```php
<?php

namespace App\Http\Integrations\Twitter;

use Saloon\Http\Connector;
use Saloon\Traits\Plugins\AcceptsJson;

class TwitterConnector extends Connector
{
    use AcceptsJson;

    public function __construct(protected string $apiKey)
    {
        $this->withTokenAuth($this->apiKey);
    }

    public function resolveBaseUrl(): string
    {
        return 'https://api.twitter.com/2';
    }

    protected function defaultHeaders(): array
    {
        return [];
    }

    protected function defaultConfig(): array
    {
        return [];
    }
}

```

To request data I created a accompanying request class to perform a tweet search looking like this:
```php
<?php

namespace App\Http\Integrations\Twitter\Requests;

use Illuminate\Support\Carbon;
use Saloon\Enums\Method;
use Saloon\Http\Request;

class SearchRecentTweets extends Request
{
    protected Method $method = Method::GET;

    public function __construct(
        protected string $query, protected Carbon $startTime, protected Carbon $endTime
    )
    {
    }

    public function resolveEndpoint(): string
    {
        return '/tweets/search/recent';
    }

    public function defaultQuery(): array
    {
        return [
            'query' => $this->query,
            'start_time' => $this->startTime->toIso8601String(),
            'end_time' => $this->endTime->toIso8601String(),
            'expansions' => 'attachments.poll_ids,attachments.media_keys,author_id,geo.place_id,in_reply_to_user_id',
            'sort_order' => 'recency',
            'max_results' => 100,
            'tweet.fields' => 'attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,public_metrics,possibly_sensitive,referenced_tweets,reply_settings,source,text,withheld',
            'user.fields' => 'created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,public_metrics,url,username,verified,withheld',
            'media.fields' => 'preview_image_url,url',
        ];
    }
}
``` 

```php
    $twitter = new TwitterV2Connector('xxx');
    $request = new SearchRecentTweets('github', now()->subMinutes(2), now());

    $response = $twitter->send($request);
```
//edit:
Even using named parameters as in the examle in the documentation does not change the output and I still get the same error message:
```php
$request = new SearchRecentTweets(query: 'cop28', startTime: now()->subMinutes(2), endTime:  now());
```

Passing the necessary request parameters should be possible via constructor parameters according to the documentattion but once I try to fire the request i get the following error message:
`Type of App\Http\Integrations\Twitter\Requests\SearchRecentTweets::$query must be Saloon\Contracts\ArrayStore (as in class Saloon\Http\Request)`

So somewhere in the hirarchy chain of the request class there muss be some class defining and typehinting the first parameter of the constructor of the request class.

I tried to identify if this was only a problem on my side but i created an empty laravel project with `laravel new` and only installed the saloon and the saloon-laravel package and the error is still present.

```
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "sammyjo20/saloon": "^2.0",
        "sammyjo20/saloon-laravel": "^2.0"
```

Is there a misunderstanding on my side or is the [documentation](https://docs.saloon.dev/the-basics/requests#using-constructor-arguments) incorrect!?

If you need more information feel free to ask.

**Comment by Sammyjo20** [comment]
Hey @effem thanks for your message 😇

I think the issue here is your `query` property on the request. The query property is already used by Saloon internally to store the query parameters object, which is an `ArrayStore`. As the error states:

> Type of App\Http\Integrations\Twitter\Requests\SearchRecentTweets::$query must be Saloon\Contracts\ArrayStore (as in class Saloon\Http\Request)

You can fix this by renaming the `query` property on your constructor to something else. Maybe `searchQuery`?

Hope this helps

Sam

**Comment by effem** [comment]
Hi, 
this is a total brain fart by me. This makes total sense and i could have come up with the solution myself.
Thanks for the quick reply and this obviously solves the problem!

**Comment by Sammyjo20** [comment]
Don't sweat it @effem sometimes a fresh pair of eyes can help!! 🚀 Happy devving :)
