### ISSUE TITLE
GetAccessTokenRequest with HasJsonBody

### ISSUE THREAD

**Issue by Darkyn** [Sammyjo20/Saloon#239]
Hello!

This is an amazing package that's really a pleasure to work with :)

The problem I'm running into is with the **getAccessToken()** method. Looking into this method, I can see that it creates a **GetAccessTokenRequest** which uses the **HasFormBody** trait. This sets the content type for the token request to "application/x-www-form-urlencoded". In my case, I need the posted content type to be JSON as this format is required by the API so that it will accept the post. 

If I change the **GetAccessTokenRequest** to use the **HasJsonBody**, the request posts correctly. Would it be possible to have the **GetAccessTokenRequest** be capable of using a JSON content type as well? Or should I just build out a new trait based on **AuthorizationCodeGrant**?

I was also thinking that maybe it would be good to have the getAccessToken method accept a request strategy so that I could use a different one that uses HasJsonBody. I dunno, just throwing it out there :)

Thanks!

**Quick update:**
The way I've solved this for the moment, is to create a new trait that extends the **AuthorizationCodeGrant** trait and overrides the getAccessToken so that I can use a custom request that uses **HasJsonBody**.

I'm thinking there might be a better way within the framework, but that's just where I'm at now,

**Comment by Sammyjo20** [comment]
Hey @Darkyn 

Many thanks for your kind message and thoughtful suggestion!

I think this is a great point - currently I don't think Saloon allows you to overwrite the entire OAuth2 request class - it will let you modify the request at run-time, but when it comes to request bodies, as they're added with traits this won't be able to be modified in the request modifier.

I wonder if adding a couple of extra methods to the `OAuthConfig` class could help with this? For example:

```php
protected function defaultOauthConfig(): OAuthConfig
{
    return OAuthConfig::make()
        ->resolveGetAccessTokenRequest(function ($args) {
                return new CustomClass($args);
        })
       ->resolveRefreshAccessTokenRequest(function ($args) {
                return new CustomClass($args);
        })
}
```

**Comment by Darkyn** [comment]
Hi @Sammyjo20 

That would be perfect, and it's keeping within the spirit of the framework. :)

**Comment by Sammyjo20** [comment]
Great, I'll get working on that!

**Comment by Darkyn** [comment]
@Sammyjo20 Awesome thanks so much! Also, apologies for creating this as an issue. I should have done it in Discussions ;)

**Comment by Sammyjo20** [comment]
No need to apologise at all @Darkyn! Appreciate the suggestion to make Saloon even better 🔥

**Comment by Sammyjo20** [comment]
Hey @Darkyn - just released this - it should all be documented here. Please let me know what you think! https://docs.saloon.dev/digging-deeper/oauth2-authentication/oauth2-authentication#using-your-own-request-classes

**Comment by Darkyn** [comment]
@Sammyjo20 Wow thank you! Looks great!! 🥇
