### ISSUE TITLE
How to handle expectations when testing?

### ISSUE THREAD

**Issue by bobmulder** [Sammyjo20/Saloon#24]
Hi all! 

Saloon is pretty cool! Helps me to integrate API's in a clean way in my Laravel application. 

However, I was wondering how to handle expectations when testing. You are able to use mocked responses, but you never know if they are called, how many times, and with which data.

I already understand how to create [fake `MockResponse`s](https://docs.saloon.dev/the-basics/testing-faking-responses/laravel), but in my tests I want to validate what data has been passed to the response, and make sure it is called (once, never on x times).

For now I came up with this solution myself:

```php

    /**
     * Helper method to mock a MockResponse object to validate if the request has been sent.
     */
    protected function mockMockResponse(mixed $data = [], int $status = 200, ?InvokedCount $expected = null): MockObject
    {
        $mock = $this->getMockBuilder(MockResponse::class)
            ->onlyMethods(['getStatus'])
            ->setConstructorArgs([ $data, $status ])
            ->getMock();

        $mock
            ->expects($expected ?: $this->once())
            ->method('getStatus')
            ->willReturn($status);

        return $mock;
    }


    // Use the mock for Saloon
    Saloon::fake([
        SendMessageRequest::class => $this->mockMockResponse(['name' => 'Sam'], 200),
    ]);
```

So I was wondering:

- Is there any preferred way I can do myself to add expectations to my API tests?
- Is there anything Saloon is missing we could add to make this easier to work? I'd be happy to help.

**Comment by Sammyjo20** [comment]
Hi @bobmulder!

Thanks for submitting your issue.

Saloon has a bunch of tests already written to ensure that the mocking is working correctly. It looks like you're using the type of mock that will respond to the specific request if it fails. Perhaps you might need to use the "sequence" test which will respond to the first Saloon request that is made and then is dropped off the list.

Perhaps I could also add an option on the MockResponse so it only occurs once?

**Comment by bobmulder** [comment]
Sorry for the delay @Sammyjo20!

Maybe my explanation wasn't that clear, sorry for that. In my case, the problem is not about having a feature where the same API is called multiple times. In fact, that is exactly what Saloon solves for me, so you have my thanks for that.

I think there are two things I am trying to do:
- Make sure the API call is called
- Make sure what data is passed to the API (and apply assertions on that)

### Make sure the API call is called

When applying your example of mocking in the docs, it won't test _if_ the request has been ehh requested:

```php

Saloon::fake([
    new MockResponse(['name' => 'Sam'], 200),
]);

``` 

This is why I mocked the `MockResponse` and adding a `exects` on the `getStatus` method to assert that the request will be called once (or twice or never or whatever):

```php

$mock = $this->getMockBuilder(MockResponse::class)
        ->onlyMethods(['getStatus'])
        ->setConstructorArgs([ $data, $status ])
        ->getMock();

$mock
        ->expects($expected ?: $this->once())
        ->method('getStatus')
        ->willReturn($status);

```

### Make sure what data is passed to the API (and apply assertions on that)

When I am mocking the response according to the docs of Saloon, I have influence of what will be returned. However, when doing so, I want to make sure as well _what_ has been sent towards the API.

Of this usecase I didn't add an example, and I do not have a solution for that yet.

Talking about mocks, in an ideal world you want to add the `with` method to validate arguments like you'd do with PHPUnit mocks.

**Comment by Sammyjo20** [comment]
Hey Bob, no worries, thanks for explaining this further.

Maybe Saloon can have assert methods on the MockClient/Facade that can be used to check if certain requests have been sent, and maybe check if the specified request data has been sent. 

For example:

`Saloon::assertSent(MyRequest::class);`
`Saloon::assertSentWith(MyRequest::class, $data)`

What do you think?

**Comment by Sammyjo20** [comment]
Or maybe something like Illuminate/Http, like this?

```php
Http::assertSent(function (Request $request) {
    return $request->hasHeader('X-First', 'foo') &&
           $request->url() == 'http://example.com/users' &&
           $request['name'] == 'Taylor' &&
           $request['role'] == 'Developer';
});
```

**Comment by Sammyjo20** [comment]
Hey @bobmulder just wanted to let you know that I'm almost finished adding these features in. Soon you will have access to the following methods:

- AssertSent (accepts request classes, closures and URL patterns)
- AssertNotSent (inverse of assert sent)
- AssertSentJson (accepts a class and an array to check both are equal)
- AssertNothingSent
- AssertSentCount

**Comment by bobmulder** [comment]
Hi Sam!

I was already preparing a reply by sniffing through the Laravel docs for examples. But your draft is truly amazing!

Personally I like the Laravel `Saloon::assertSent(GetForgeServerRequest::class);` style because it is very close to what Laravel does wit jobs, queues, facades, mailables, et cetera.

Is there anything you want me to do? Since this is open source stuff 😉

**Comment by Sammyjo20** [comment]
I’m super happy you like it! 

I think it’s pretty much done, I just want to run a few more tests and maybe install it on a local version of Laravel before I publish a release so just sit tight for another day or two!

**Comment by bobmulder** [comment]
I can handle that ;) Thank you for the effort!
