### ISSUE TITLE
How to add array to Query Params?

### ISSUE THREAD

**Issue by derpoho** [Sammyjo20/Saloon#240]
Howdy!

i am wondering how i can add an array to the query params?

I got the issue here on the Pinecone Library: https://github.com/probots-io/pinecone-php/issues/3

Basically i need to send HOSTNAME/vectors/fetch?ids=vector-id-1&ids=vector-id-2
But the current implementation is wrong, since i join the ids with comma, which isn't supported by pinecone.
Here is the current relevant part in the code: https://github.com/probots-io/pinecone-php/blob/master/src/Requests/Index/Vectors/Fetch.php#L58

i tried setting the ids as an array, but thats not working either.

Any ideas?

**Comment by Sammyjo20** [comment]
Hey @derpoho 

This is a bit of a tricky one, and a strange implementation of query parameters from Pinecone's API side - I wonder if this is a standard of query parameter arrays that I'm not aware of. I'll have to do some digging.

Currently, Saloon has a `ArrayStore` which expects `keys` and `values` as the query parameters. I wonder if there's a way that the user could set the query parameters (even at a string level) before the request is sent. Within version 3, I will be constructing a PSR-17 URI class based on the URL and query parameters - I wonder if this could be modified for such situations.

Going back to version two though... I wonder if I could implement some sort of DTO as the value, in these very custom situations...

```php
protected function defaultQuery(): array
{
     return [
         'id' => Query::list([1, 2, 3]); // By default will create ?id=1&id=2&id=3
         'name' => Query::list([1, 2, 3], ','); // With the separator it could do ?id=1,2,3
     ];
}
```

I'll have to see if Guzzle will accept this kind of implementation 😅

**Comment by derpoho** [comment]
Thanks for the reply! It's definitely not standard by Pinecone ;) But anyway, for now i have fixed it by applying middleware to guzzle and rewriting the query 🙈 Ugly, but works for now. 

I am not sure if you even should support that case, is it worth the effort? 

After some digging i found some examples for that one, but everybody is bashing the implementation on the API Side ;)

**Comment by Sammyjo20** [comment]
Hmm I personally can't see any place where this kind of logic is implemented 😅 I've certainly not experienced it but I won't put it past some of the APIs that I deal with.

I reckon from version three I could build up the PSR-17 URI and then allow it to be modified, so at least you don't have to go right into Guzzle to modify it - or maybe even provide a `onPsrRequest` method that is invoked to allow people to modify/debug the PSR request **right** before it's sent (from v3) 💡

**Comment by Sammyjo20** [comment]
I agree with what you said though @derpoho - I don't think this is something Saloon should cater for in the query parameters but I will implement the hook I mentioned above so people can modify the PSR request 👍 

P.S: Amazing work on the Pinecone SDK - looks awesome.

**Comment by derpoho** [comment]
@Sammyjo20 Do you have an update on this since V3 is out now? I am currently rebuilding Pinecone PHP to use V3 and i am now trying to fix the issue forever ;)
