### ISSUE TITLE
Using `MockClient` in your app, and not in tests, seems to append 'public' to the fixtures path.

### ISSUE THREAD

**Issue by danmatthews** [Sammyjo20/Saloon#245]
I was using the mockclient to get some base fixtures while making the actual calls in my app running in the browser and it appears to have appended 'public' to the start of the fixtures path:

`public/tests/Fixtures/Saloon/{myfixture}`

I haven't had time to dive in to submit a PR, but i'm guessing that it's using the `__DIR__` or script base path, which might be causing this?

This also happens even if you explicitly set the path using `MockConfig`:

```
// Still happens
MockConfig::setFixturePath('tests/Fixtures/Saloon');
```

**Comment by danmatthews** [comment]
`vendor/sammyjo20/saloon/src/Http/Faking/Fixture.php:46`

```
// Called in tinkerwell, produces: "tests/Fixtures/Saloon"
(new Saloon\Helpers\Storage(\Saloon\Helpers\MockConfig::getFixturePath()))->getBaseDirectory();
```

Called in the browser, produces:

<img width="303" alt="CleanShot 2023-06-26 at 11 53 22@2x" src="https://github.com/Sammyjo20/Saloon/assets/149426/cbd1db75-3c79-47f2-b865-ff114681905b">

Which, should be fine!

**Comment by danmatthews** [comment]
But yet weirdly still produces the output at `public/`:

<img width="489" alt="CleanShot 2023-06-26 at 11 54 49@2x" src="https://github.com/Sammyjo20/Saloon/assets/149426/638ed074-286f-407d-9473-7b63430cdaf2">

**Comment by danmatthews** [comment]
I think it's: `vendor/sammyjo20/saloon/src/Helpers/Storage.php:112`

`file_put_contents` is probably operating within `public/` ,might be better to move to use 

`file_put_contents(base_path($fullPath), $contents));` or something similar? Will try and test when I can.

**Comment by danmatthews** [comment]
<img width="388" alt="CleanShot 2023-06-26 at 12 08 46@2x" src="https://github.com/Sammyjo20/Saloon/assets/149426/c8cce24e-530b-4132-99aa-869f6d472dc2">

`base_path` fixes it at least for this instance, will pull a copy of the package, PR + run tests in a second.

**Comment by Sammyjo20** [comment]
Hey @danmatthews as mentioned in my PR comment, I think this fix is better suited in the service provider in the Laravel side of things - the reason this is happening is because PHP is running it relative the directory its in. If you're using the browser, then it'll run the code in the index.php, so it'll try to use /public/tests.
