### ISSUE TITLE
`defaultAuth` in a connector seems to not be applied

### ISSUE THREAD

**Issue by simonhamp** [Sammyjo20/Saloon#249]
I'm writing a connector and trying to use `defaultAuth` per [the docs](https://docs.saloon.dev/the-basics/authentication#default-authentication), but when I create the connector instance and try to send a request through it, the authenticator always resolves to `null`

What might I be doing wrong?

**Comment by simonhamp** [comment]
Ignore me. I'm being dumb. It's there, it's just removed from dumps...

**Comment by Sammyjo20** [comment]
Hey @simonhamp 

Glad you managed to resolve the issue! It’s actually going to be changed from v3 so a lot of the authentication will happen on-demand (like bearer token, query, etc) but then there may be “deferred Authenticators” which will have additional logic inside like fetching an authentication token :)
