### ISSUE TITLE
How to stream upload files via MultipartValue?

### ISSUE THREAD

**Issue by georgeboot** [Sammyjo20/Saloon#260]
We have to upload relatively large files (~300MB) to an API. The files are stored on blob storage.
I have seen that I can stream the entire body of a request, but what I want is to attach a file via a `MultipartValue` but stream that instead, so I don't have to put the whole file into memory.

Is this a possibility?

**Comment by Sammyjo20** [comment]
Hey @georgeboot! 

You can actually provide a stream or a resource inside of the MultipartValue for uploading large requests - like this...

```php
protected function defaultBody(): array
{
      return [
             new MultipartValue(name: 'picture', value: fopen('some/path.txt', 'r')),
      ];
}
```

Let me know if this works for you.

**Comment by georgeboot** [comment]
I'm not sure what I did wrong but I can confirm that this works! Apologies, my bad!
