### ISSUE TITLE
Generate from OpenAPI Spec

### ISSUE THREAD

**Issue by bobbyshaw** [Sammyjo20/Saloon#262]
Hi,

Thanks for this great package! I've been looking into using it to generate a better SDK than the one I hand-rolled for my BigCommerce projects. Their API surface area is large and constantly evolving so I was just wondering if there was any prior art in generating request classes (and responses?) from a published schema, e.g. https://github.com/bigcommerce/api-specs, rather than manually writing it all ourselves. 

Thanks in advance.

**Comment by Sammyjo20** [comment]
Hey @bobbyshaw 

This is something I have been interested in building for a while! :) It's not available yet, but it certainly could be in the future. I was considering using something like NativePHP to provide a really nice UI to "import" Saloon requests from OpenAPI.

**Comment by bobbyshaw** [comment]
Hi @Sammyjo20, that would be great! 

Haha, I actually saw your tweet about that yesterday. NativePHP has certainly opened up a lot of exciting new opportunities! For what it's worth coming from a random person on the internet, I'd like to be able to incorporate this into the same repository as the SDK so that it is easy for maintainers to re-run as necessary without needing to download separate tools.

For further context, we have something similar set up for our node SDK. https://github.com/Space48/bigcommerce-api-js/tree/master/src/internal/reference

**Comment by Sammyjo20** [comment]
Hey @bobbyshaw this is now a thing! Thanks to the brilliant community, @HelgeSverre has made: https://github.com/crescat-io/saloon-sdk-generator which supports OpenAPI. Please do try this out and post issues to help improve it 🙌
