### ISSUE TITLE
Paginator empty after ->count()

### ISSUE THREAD

**Issue by Joel-Jensen** [Sammyjo20/Saloon#263]
Hi! Know that there is an new paginator on it's way so maybe this bug isn't relevant anymore but just in case it will follow along:

For some reason it seems that the collection is empty the next call if you do ->count() on the paginator, lazy or not does not seem to make a difference. This is when using Saloon::fake() if that might make a difference.
```
ray($search->collect('Customers', lazy: false)); // 1 item
if ($search->count() > 0) { // true
    ray($search->collect('Customers', lazy: false)); // empty
    ray($search->collect('Customers', lazy: false)); // second call, from now on it works. 1 item
}
```

As I said, might not be relevant, so feel free to close without any further notice :)

**Comment by juse-less** [comment]
Hey, @Joel-Jensen.

I have a theory on why this is, but I'd prefer if I could see more code, to be sure.
Could you possibly include the whole part of the code, including the instantiation of the paginator, and all that?

Most importantly, though: Which paginator are you using?
Each paginator will have some logic around iterating and/or resetting, which is why it's important to know.

My theory is around how iterators works, and, possibly, the resumable functionality.
But I would prefer to see more code to understand everything that happens.

**Comment by Joel-Jensen** [comment]
Right, should have included that from the start, sorry.

Connector.php
```php
public function paginate(Request $request, mixed ...$additionalArguments): PagedPaginator
{
    $paginator = (new PagedPaginator($this, $request, $this->pageLimit, ...$additionalArguments))
        ->setTotalKeyName('MetaInformation.@TotalPages')
        ->setCurrentPage(1);
}
```

With one minor change on that class though because of how the API works, if that might affect the result:
```php
public function totalPages(): int
{
    return $this->totalResults();
}
```

My Customer resource:
```php
public function all(array $queryParams = []): PagedPaginator
{
  return $this->connector->paginate(
      (new ListRequest("{$this->basePath}", $queryParams))
          ->rootEndpoint($this->rootEndpoint)
          ->fromResponse($this->fromResponseClass())
  );
}
```

List Request
```php
class ListRequest extends Request
{
    use HasResource;

    protected Method $method = Method::GET;

    public function __construct(
        protected string $url,
        protected array $queryParams = [],
    ) {
        foreach ($queryParams as $key => $value) {
            $this->query()->add($key, $value);
        }
    }

    public function fromResponseClass(): ?string
    {
        return $this->fromResponse;
    }
}
```

If you need the whole connector with oAuth etc. you can see it here: https://gist.github.com/Joel-Jensen/a136f27f56fef671677fee3cd92e5162

Let me know if you need anything else.

**Comment by juse-less** [comment]
Hmm. I've tried writing tests based on your information, but I just can't seem to be able to replicate the problem.

I've tried both manually looping with foreach, as well as 'collecting' the paginator.
It works every time without issues.
I also do assert with count() in-between loops/collects, which shows the correct number of items, just like it does for you.
But the 2nd and 3rd request all work correctly for me.

I tried the PagedPaginator specifically, as that's the one you had issues with.
I could also try the same with the others, but it feels like it's not gonna matter before I can replicate the issue.

That being said - @Joel-Jensen could you try without the cache plugin/trait, and maybe the other plugins, to see if it changes anything?

I'll poke around a bit more to see if I can make it fail for me.

**Comment by juse-less** [comment]
Right.. before I forget..
`Paginator::count()` returning more than 0 is to be expected, as most APIs will have data on an endpoint.
It returns the number of pages/requests available.
Like a total_pages property on a response from the API.

But the 2nd `Paginator::collect()` should definitely return the result set from all requests (number from `Paginator::count()`), just like the first and third `Paginator::collect()`.
That's specifically the issue I'm looking into replicating.

**Comment by Joel-Jensen** [comment]
Sooo, after huge amount of debugging and trying to recreate it as a basic case as possible, it turned out to be my bit modified PagedPaginator that was out of sync with the real one. Very sorry for wasting your time with such a stupid bugg...

**Comment by juse-less** [comment]
No problem.
Sometimes we just need an extra set of eyes when we rip our hair out.
It happens to everyone.

I'm glad you figured it out. 🙂
