### ISSUE TITLE
Artisan command does not work

### ISSUE THREAD

**Issue by pajkho** [Sammyjo20/Saloon#265]
When using the below artisan command I get an error as below. Is it not implemented yet or am I doing something wrong? I cannot find the actual commands in the code.

php artisan saloon:connector <Integration Name> <Connector Name>

   ERROR  There are no commands defined in the "saloon" namespace.

**Comment by Lirianer** [comment]
Hi @pajkho! 

The namespace is part of the [saloon-laravel](https://github.com/Sammyjo20/saloon-laravel) plugin mentioned in the [documentation](https://docs.saloon.dev/official-plugins/laravel-integration) and, from my understanding, not required when installing the saloon package. 

Have you required the laravel plugin package?

Do you have a list of steps to reproduce the problem?

Thanks!

**Comment by Sammyjo20** [comment]
That's right @Lirianer - thanks for helping! 😀

You can install the Saloon Laravel plugin by running: `composer require sammyjo20/saloon-laravel` - this should register the commands that are missing.

I'll also update the docs to make it clearer that you need the Laravel plugin installed.

**Comment by pajkho** [comment]
Thank you. I totally missed that part of the documentation :)
