### ISSUE TITLE
Request URL overwrite not working

### ISSUE THREAD

**Issue by StanBarrows** [Sammyjo20/Saloon#267]
Hey Sammy

I must use a different URL within the Connector class than in all other requests classes. The docs mention that just a fully qualified URL has to be provided to overwrite the Basel URL. 

<img width="810" alt="CleanShot 2023-08-09 at 03 52 27@2x" src="https://github.com/Sammyjo20/Saloon/assets/10268813/6cde7919-282e-4ed1-945c-d828bf721d85">

But somehow, the URLs get concatenated. Do you have any idea how to solve this? 

![CleanShot 2023-08-09 at 03 53 27@2x](https://github.com/Sammyjo20/Saloon/assets/10268813/66a80522-1f36-4b47-9602-244943999364)

## Connector

```
class MicrosoftConnector extends Connector
{
	use ClientCredentialsGrant;

	public function resolveBaseUrl(): string
	{
		return "https://login.windows.net";
	}

	protected function defaultOauthConfig(): OAuthConfig
	{
		$microsoft = config('services.microsoft');

		$tenant = Arr::get($microsoft, 'tenant');

		return OAuthConfig::make()
			->setClientId(Arr::get($microsoft, 'client_id'))
			->setClientSecret(Arr::get($microsoft, 'client_secret'))
			->setTokenEndpoint("/$tenant/oauth2/token");
	}
}
```

## Request
```
class OrderPositionsRequest extends Request
{
	protected Method $method = Method::GET;

	public function resolveEndpoint(): string
	{
		return 'https://tenant-instance-d365-fo.com/data/PurchaseOrderLines?$filter=PurchaseOrderNumber eq ' . $this->orderId;
	}

	public function __construct(
		protected string $orderId,
	)
	{

	}
}
```

Best regards
Sebastian

**Comment by Sammyjo20** [comment]
Hey @StanBarrows I think it might be something about the leading `/` you have in your `OAuthConfig` - 

Have you tried removing the forward slash and see if it works from there?

```php
->setTokenEndpoint("$tenant/oauth2/token");
```

**Comment by Sammyjo20** [comment]
Hey @StanBarrows! Did this fix work for you? :)

**Comment by Sammyjo20** [comment]
I'm going to close this issue for now but please do re-open if the issue persists @StanBarrows - many thanks!
