### ISSUE TITLE
cacheable OAuth Request

### ISSUE THREAD

**Issue by sawirricardo** [Sammyjo20/Saloon#273]
When we add HasCaching in OAuthConnector, it also requires the oauthRequest to be cacheable, which currently is not

**Comment by Sammyjo20** [comment]
Hey @sawirricardo - if you need to add caching to the OAuthRequest - you'll need to make your own class that extends this request, and then define this custom class in the OAuth connector. The reason it requires an interface is because the interface requires some specific methods to be defined.

https://docs.saloon.dev/digging-deeper/oauth2-authentication/oauth2-authentication#using-your-own-request-classes

**Comment by sawirricardo** [comment]
I ended up using that way 👍 I think it's a good idea to note about this in docs? I don't know if caching oauth request is the recommended one, but maybe as someone who uses this, my first impression is to put the caching trait in the connector instead of the request (since the docs only explains to use connector instead of tinkering with the request itself)

**Comment by Sammyjo20** [comment]
Caching the OAuth request is not something I would recommend if I'm honest - if it's the access tokens you want to cache, I would just store the authenticator securely in cache separately. If it happens again I will put a note in the docs. Thank you!

**Comment by sawirricardo** [comment]
What do you suggest in this situation? Usually ill cache to 1:59 time limit, and if that expires, just ask the oauth again, using cache() remember method...

**Comment by Sammyjo20** [comment]
Are you able to share some of your code?

**Comment by sawirricardo** [comment]
```
<?php

class MyIntegrationConnector extends SaloonConnector
{
public function construct()
{
    $this->withAuthentication(cache()->remember('access_token', now()->addMinutes(119), function () {
        return (new OauthConnector)->getAccessToken();
    }));
}
}
```

**Comment by Sammyjo20** [comment]
Oh yeah that looks absolutely fine! :) In the past, I've serialized and stored the authenticator in the database, but this is also a good idea.

**Comment by sawirricardo** [comment]
😃👍

What does the authenticator looked like, if you dont mind?
