### ISSUE TITLE
Feature Request: Cookies Implimentation

### ISSUE THREAD

**Issue by RhysLees** [Sammyjo20/Saloon#274]
For a project im working on i need to get and set cookies for requests, currently i have to manually add a new Guzzle Cookie Jar and attach it to the config of the Request or Connector like so:

```php
$jar = new CookieJar();

$connection = new Connector();

$request = new Request();
$request->config()->add('cookies', $jar);

$response = $connection->send($request);
        
$cookies = $jar->toArray();
```

This seems a little messy compared to Laravels Http client where methods such as `->withCookies(array $cookies, string $domain)` and `$response->cookies();` exist.

**Comment by Sammyjo20** [comment]
Hey @RhysLees you can always set this up on your connector or request using the `defaultConfig` method if you don't want to define it every time you use the request.

```php
protected function defaultConfig(): array
{
    // Maybe this could be set in the constructor

    $this->cookieJar = new CookieJar;

    return [
        'cookies' => $this->cookieJar 
    ];
}

// Then make a getter for grabbing the cookie jar? 

public function getCookieJar(): CookieJar
{
    return $this->cookieJar;
}
```

Then you can use the `$request->getCookieJar()`

Totally understand this doesn't feel completely joined together. I'll definitely add it to my list of things to look at after I get v3 out of the door in a couple of weeks 👍 

I like the idea of adding `$response->cookies()` - I'll look into doing something like that, but to suit Saloon

**Comment by RhysLees** [comment]
Perfect!

**Comment by juse-less** [comment]
The overall problem with cookies is that PSR-7 doesn't support this.
So Sam/Saloon would need to correctly manage- and format/parse cookies per the RFCs, and apply/read the relevant cookie headers (they are different in request and response).

This is one of the upsides of using something like Guzzle directly, rather than supporting PSR.

@Sammyjo20 I guess, you could look at how Guzzle does it. 🙂

**Comment by Sammyjo20** [comment]
Closing this for now @RhysLees as it's on my list of things to look at for v4 - feel free to reopen if you have any questions.

**Comment by innocenzi** [comment]
@Sammyjo20 Stumbled upon that issue recently—would be great to have first-party support for cookies, so they can be stored in fixtures as well!
