### ISSUE TITLE
documentation offline ?

### ISSUE THREAD

**Issue by dreammonkey** [Sammyjo20/Saloon#288]
It seems the documentation has been offline for quite a while...

The response is timing out for me..

https://docs.saloon.dev/

**Comment by Sammyjo20** [comment]
Hey @dreammonkey!

Seems like it's all up and online for me and I checked a few sites which also report they are online. Does it work on your phone using mobile data / 4G/5G?

You can view the docs on Github here as a last resort! :) https://github.com/sammyjo20/saloon-docs

**Comment by dreammonkey** [comment]
You are indeed right.
It seems the website is unreachable through my company's network.
Accessing it via mobile data works.

Sorry for this non issue.
Keep up the great work !
