### ISSUE TITLE
A facade root has not been set

### ISSUE THREAD

**Issue by ulfie22** [Sammyjo20/Saloon#292]
I am upgrading from v1 to v2 and trying to improve my test suite with a complete set of mocks (I have 22 requests). I am using Pest for testing. I am trying the simple case of logging into a remote API. The code basically looks like:

```
use Saloon\Http\Faking\MockResponse;
use Saloon\Laravel\Facades\Saloon;

test('can set up mock data', function () {
    Saloon::fake([
        Login::class => MockResponse::fixture(
            'Login.json'
        ),
    ]);


    $connector = new \App\Http\Integrations\MainConnector();
    $request = new \App\Http\Integrations\Requests\Authentication\Login(
        'username', 'password'
    );

    $response = $connector->send($request);
    expect($response->status())->toBe(200);
});
```

When I run the test, I get this error:

`RuntimeException: A facade root has not been set.`

I had mocking/fixtures working correctly in v1 without encountering this error. Can someone please suggest how to get around this?  Thanks!

**Comment by Sammyjo20** [comment]
Hey @ulfie22 

Sorry to hear you're having some trouble. 

That error usually occurs when running tests that aren't properly configured for a Laravel environment. Just checking - are you using Laravel? If so, which version are you using?

**Comment by ulfie22** [comment]
Hi Sam - Thank you for your quick reply and thanks so much for Saloon! Yes, running Laravel, the latest version, and it looks to be a PHPUnit configuration issue. I'm trying to put all the tests that actually have to hit an outside API in one folder away from our other tests, so that when we run our main test suite, it will completely rely on generated fixtures. When I put the test above in our existing directory structure, it works correctly. I will sort it out.

One unrelated question: we have several requests that rely on DTOs. In v1, I added the CastsToDTO trait. I didn't find explicitly what to do with these, but I've removed the trait and added this method:

```
public function createDtoFromResponse(Response|\Saloon\Contracts\Response $response): object
```
and cleaned up the parameters of the actual DTO class. Is that correct?

Thanks again!!

**Comment by Sammyjo20** [comment]
Hey @ulfie22 

Yep - that's correct! The `CastsToDto` trait was removed in v2 in favour of the built-in `createDtoFromResponse` method. 

Thank you for your kind words and have a great day!

**Comment by ulfie22** [comment]
If someone ends up here because of a search, the correct answer is to make sure you have Pest properly configured to recognize your top level directories where your tests live. In my case, this was simply adding the directory to this line in Pest.php file:
```
uses(Tests\TestCase::class)->in('Feature', 'Unit', 'NEW_TOP_LEVEL_TEST_DIRECTORY');
```

**Comment by bianchi** [comment]
To future people looking for this.

If you are using Laravel that can happen if you import PhpUnit TestCase instead of the Laravel one.

`use PHPUnit\Framework\TestCase`

instead of:

`use Illuminate\Foundation\Testing\TestCase`
