### ISSUE TITLE
Upgrade from v1 composer confusion...

### ISSUE THREAD

**Issue by ulfie22** [Sammyjo20/Saloon#293]
In the "Upgrade from v1" instructions, it says to require (for Laravel):
```
"sammyjo20/saloon": "^2.0",
"sammyjo20/saloon-laravel": "^2.0"
```
I believe it should be:
```
"saloonphp/saloon": "^2.0",
"saloonphp/laravel-plugin": "^2.0",
```
I couldn't find a place to make a PR for this change, so if it is possible to do that, I apologize for posting this here.

**Comment by Sammyjo20** [comment]
Hey @ulfie22 many thanks for noticing this, I completely missed that! I have now updated the upgrade guide. For your future reference if you're interested - you can see and contribute to the docs here: https://github.com/sammyjo20/saloon-docs

Many thanks for your sponsorship too, it's greatly appreciated 🙌
