### ISSUE TITLE
Error when only connector has a body and request does not

### ISSUE THREAD

**Issue by jeffreyvanhees** [Sammyjo20/Saloon#311]
I have a situation with a Connector that implements the `HasBody`-interface and a Request that doesn't. Now I'm getting an `__clone method called on non-object`-error.

I think it's because of the following code: https://github.com/saloonphp/saloon/blob/dc0284d6dcbe21ee7f4e0fe746a75c7431e7fba5/src/Http/PendingRequest/MergeBody.php#L43

It tries to clone `$requestBody` while it's `null` and then fails, which is strange because of the null coalescing operator (`??`).

When I implement the `HasBody`-interface to my Request too, the error disappears.

_PHP version: 8.2.7_

**Comment by Sammyjo20** [comment]
Hey @jeffreyvanhees! Thanks for finding this issue - I've just released a fix for the issue -  please could you update Saloon in your project and let me know if you're still having the same issue? Thank you 🙏

**Comment by jeffreyvanhees** [comment]
Works perfectly! You're welcome and thanks for the quick fix (and Saloon itself, of course! 🙏).
