### ISSUE TITLE
Removal of key customisation in pagination?

### ISSUE THREAD

**Issue by carnevalle** [Sammyjo20/Saloon#316]
Hi

I just upgraded to the V3 of Saloon and noticed that customisation of keys has been removed in the new Pagination-plugin?

In the OffsetPaginator for instance it is now hardcoded that the keys are 'limit' and 'offset', where it previously was possible to customise.

OffsetPaginator V3
```php
$request->query()->merge([
    'limit' => $this->perPageLimit,
    'offset' => $this->getOffset(),
]);
```

OffsetPaginator V2
```php
$request->query()->merge([
    $this->getLimitKeyName() => $this->limit(),
    $this->getOffsetKeyName() => $this->currentOffset(),
]);
```

Of course I can just create my own Paginator or extend and override the class, but it seems a bit more tedious than to just do, what I did in V2
```php
$paginator
    ->setLimitKeyName('batch')
    ->setOffsetKeyName('skip')
    ->setTotalKeyName('Result.Count');
```

**Comment by Sammyjo20** [comment]
Hey @carnevalle, welcome to v3! 🙌

The best way to overwrite this is from within the paginator you have created on your connector. You can extend the `applyPagination` method and just change the query parameters which are being sent.

```php
protected function applyPagination(Request $request): Request
{
    $request->query()->merge([
        'top' => $this->perPageLimit,
        'skip' => $this->getOffset(),
    ]);

    return $request;
}
```

https://docs.saloon.dev/digging-deeper/pagination/limit-offset-pagination#assumptions-made-with-the-offsetpaginator

**Comment by Sammyjo20** [comment]
Hey @carnevalle I'm going to close this issue for now but feel free to re-open if this doesn't fix the issue ☺️ Have a great day.
