### ISSUE TITLE
Inquiring about the Option to Send the Path of a Certificate

### ISSUE THREAD

**Issue by wilderamorim** [Sammyjo20/Saloon#317]
While using the library, I came across the need to send the path of a certificate along with my requests.

I've looked at the documentation and the resources available, but I couldn't find any explicit information about the option to include the path of a certificate in the request. I would greatly appreciate it if those responsible for maintenance could confirm whether this functionality is available in the library.

**Comment by Sammyjo20** [comment]
Hey @wilderamorim1 

I believe what you're looking for is the `cert` option which is provided by Guzzle. You can apply this option in Saloon via "config" which can be applied in many different ways, but I'll assume you're going to need the certificate on the connector.

```php
protected function defaultConfig(): array
{
     return [
          'cert' => ['/path/to/certificate', 'certificatepassword'],
     ];
}
```

You can see more here: https://docs.saloon.dev/the-basics/http-client-config

The Guzzle option: https://docs.guzzlephp.org/en/stable/request-options.html#cert

**Comment by Sammyjo20** [comment]
Hey @wilderamorim I'm going to close this issue for now but feel free to re-open if this doesn't answer your question ☺️ Have a great day.
