### ISSUE TITLE
InvalidArgumentException: A 'contents' key is required

### ISSUE THREAD

**Issue by ManukMinasyan** [Sammyjo20/Saloon#331]
When attempting to send multiple values using Multipart Form Body, I encounter an error. While this functionality worked seamlessly in version 2, it appears to be malfunctioning in version 3.

Issue: https://flareapp.io/share/qm1e8Dwm

**Comment by Sammyjo20** [comment]
Thanks for making a separate issue. I'll take a look for you 👍

**Comment by Sammyjo20** [comment]
Hey @ManukMinasyan I believe I have found and fixed the issue in the latest release. Please could you run `composer update saloonphp/saloon` and try again?

**Comment by ManukMinasyan** [comment]
Hi @Sammyjo20 Yeah, this issue is successfully resolved. Thank you very much.
