### ISSUE TITLE
AuthConnector::createOAuthAuthenticator(): Argument #2 ($refreshToken) must be of type string, null given

### ISSUE THREAD

**Issue by ithuis** [Sammyjo20/Saloon#352]
i dont get a refresh token ( shopify api ) and dont have a fallback. 

should't the $refreshToken be Nullable

```
protected function createOAuthAuthenticator(string $accessToken, ?string $refreshToken, ?DateTimeImmutable $expiresAt = null): OAuthAuthenticator
    {
        return new AccessTokenAuthenticator($accessToken, $refreshToken, $expiresAt);
    }
```

in AccessTokenAuthenticator the refresh is also nullable
```
 public function __construct(
        public readonly string             $accessToken,
        public readonly ?string            $refreshToken = null,
        public readonly ?DateTimeImmutable $expiresAt = null,
    ) {
        //
    }
```

**Comment by Sammyjo20** [comment]
Hey @ithuis 

What version of Saloon are you using? Are you able to send me the result of the following:

```bash
composer show | grep "saloon"
```

**Comment by ithuis** [comment]
this is what i am using now:

saloonphp/cache-plugin                v3.0.0
saloonphp/laravel-http-sender         v2.1.0
saloonphp/laravel-plugin              v3.2.0
saloonphp/pagination-plugin           v2.2.0
saloonphp/rate-limit-plugin           v2.0.0
saloonphp/saloon                      v3.4.0

**Comment by ithuis** [comment]
is there anything i can do for this?

**Comment by Sammyjo20** [comment]
Apologies for the delay @ithuis I have fixed this issue so now the default stub allows a nullable refresh token.

**Comment by ithuis** [comment]
? no apologies needed.. you made this great package.. thank you!
