### ISSUE TITLE
`HasReponse` trait causes exception

### ISSUE THREAD

**Issue by aerni** [Sammyjo20/Saloon#353]
I'm following the docs on [Accessing the response from your DTO](https://docs.saloon.dev/digging-deeper/data-transfer-objects#accessing-the-response-from-your-dto). However, adding the `HasReponse` trait causes this exception:

```
Readonly class App\Data\Event cannot use trait with a non-readonly property Saloon\Traits\Responses\HasResponse::$response
```

Changing the property to `readonly` resolves the issue. Happy to submit a quick PR, but I'm not sure if this change causes any issues? I couldn't find any tests.

https://github.com/saloonphp/saloon/blob/257ff2c29fccb69d9a277e1627871df9c38669de/src/Traits/Responses/HasResponse.php#L14

**Comment by Sammyjo20** [comment]
Hey @aerni I'm not sure we can safely make this property readonly without a breaking change. Are you able to remove the `readonly` from your class definition and make each property readonly instead?

**Comment by aerni** [comment]
Sure, I can do that. I was just confused that it didn't work, as I copied exactly as mentioned in the docs. Probably a good idea to update that code example in the docs then.

**Comment by Sammyjo20** [comment]
Ahh good point, I'm sorry about that. I've updated the docs @aerni .

**Comment by aerni** [comment]
All good. Thanks for the prompt response! Really digging Saloon! ❤️

**Comment by Sammyjo20** [comment]
I'm glad to hear that! 🤠❤️ Yeehaw!
