### ISSUE TITLE
`HasReponse` only works on single item

### ISSUE THREAD

**Issue by aerni** [Sammyjo20/Saloon#355]
I'm following the docs on how to [add the response to a DTO](https://docs.saloon.dev/digging-deeper/data-transfer-objects#accessing-the-response-from-your-dto). This works as expected for a single item like a server. 

If you've got a response containing multiple items (servers), you can create a DTO for each server. [Similar to this example](https://github.com/saloonphp/saloon/discussions/186) in the discussion.

However, the response won't be added to each individual DTO. I am not sure if this is a bug or a missing feature.

**Comment by Sammyjo20** [comment]
Hey @aerni this is expected behaviour I'm afraid. If you need to include the response on every DTO you should pass it into your DTO yourself. Perhaps you could implement your own solution like:

```php
<?php

class DTO {
     public function __construct(
          public Response $response,
          public string $otherProperty,
          // etc...
     )
     {}
}
```
