### ISSUE TITLE
Typing of responses with DTO's

### ISSUE THREAD

**Issue by falko100** [Sammyjo20/Saloon#358]
So I have a problem with typing / phpstan / intellij.

```php
$connector = new \App\Http\Integrations\GenericWebshopSoftware();
$request = new \App\Http\Integrations\GenericWebshopSoftware\Requests\GetProductsRequest();
$response = $connector->send($request);
$dto = $response->dto();
```

The return type of `$dto` is `mixed` because `$connector->send` returns a generic Response instead of my `\App\Http\Integrations\GenericWebshopSoftware\Responses\GetProductsResponse`.

Is there any way to get this working in Saloon?
We want to integrate Saloon into our default stack, but this would be a no-go due to our strict phpstan policy.

**Comment by Cbrad24** [comment]
I'm not too familiar with PhpStan but this is how I get around the typing / IntelliJ aspect of it:

```php
$connector = new cPanelConnector();
$response = $connector->send(new GetTenantsRequest);

/** @var \Illuminate\Support\Collection<int, \App\Http\Integrations\cPanel\DataObjects\Tenant> $tenants */
$tenants = $response
    ->dto()
    ->keyBy('id');
```

By injecting a `@var` DocBlock  IntelliJ now knows what type of variable I am working with and can show the appropriate type hints.

![image](https://github.com/saloonphp/saloon/assets/2669153/afa7cfb2-c6b6-462d-8fa0-1811d7bdbbaa)

![image](https://github.com/saloonphp/saloon/assets/2669153/5293708e-db1d-4373-8b75-2e38b7caf2e5)

Not sure if this will override PhpStan but the `@var` DocBlock has come in handy a few times for me to unwrap some of Laravel's and other packages magic.

**Comment by Sammyjo20** [comment]
+1 on the above solution - I will take a look at generics and see if there's a way even with a template that I can allow people to define the types of DTOs being returned.

**Comment by Sammyjo20** [comment]
Hey @falko100 @Cbrad24 

I have updated the documentation to include a section on improving IntelliJ / Type detection for Saloon's DTOs. I have recommended two solutions - using the suggestion by @Cbrad24 but also using the `createDtoFromResponse()` which will have direct typed support which might be nicer.

https://docs.saloon.dev/digging-deeper/data-transfer-objects#phpstan-typehinting-dtos

Thanks again for the good discussion!

**Comment by benjibee** [comment]
I'd like to add my preference to the options here. I use the resource pattern [as described in the docs](https://docs.saloon.dev/digging-deeper/building-sdks#request-resources-groups) and then type hint the data objects or structured arrays, making everyone happy:
```php

class TemplateResource extends BaseResource
{
    /**
     * Get the details of a specific template.
     */
    public function get(string $templateId): TemplateDataObject
    {
        return $this->connector->send(new GetTemplateRequest($templateId))->dtoOrFail();
    }

    /**
     * Get all templates.
     *
     * @return Collection<int, TemplateDataObject>
     */
    public function all(): Collection
    {
        return $this->connector->send(new GetTemplatesRequest())->dtoOrFail();
    }
}
```

As a bonus I also add the resource as a method to the connector as such:
```php
/**
 * Get access to template-related requests.
 */
public function templates(): TemplateResource
{
    return new TemplateResource($this);
}
```

This allows full type hinting wherever it's used:
```php
public function __construct(
    private readonly TemplateServiceConnector $connector,
) {}

/**
 * Get all templates from this service.
 * 
 * @return Collection<string, string>
 */
public function getTemplates(): Collection
{
    try {
        return $this->connector->templates()->all()->pluck('name', 'id');
    } catch (Exception) {
        return collect();
    }
}
```
