### ISSUE TITLE
Paginator Next Request URL help

### ISSUE THREAD

**Issue by avenjamin** [Sammyjo20/Saloon#366]
Howdy,

Not sure if I'm confused or not but I'm trying to use the Microsoft Graph API to get a list of users.
When I make a request I get a `@odata.nextLink` field in the JSON response.
This URL is similar to the original request endpoint but has a $skiptoken or a $skip query parameter added.

I'm looking at custom `Pagination` but I can't work out how to modify the `$request` to use the URL in the `@odata.nextLink` field.

I assume this should be done in the `applyPagination` function but just not sure how best to change the URL.

``` PHP
protected function applyPagination(Request $request): Request
{
    if ($this->currentResponse instanceof Response) {
        // Something like this?
        $request->setEndpoint($this->currentResponse->json('@odata.nextLink'));
    }

    return $request;
}
```

Microsoft say:
 
> Important
> You should include the entire URL in the @odata.nextLink property in your request for the next page of results. Depending on the API that the query is being performed against, the @odata.nextLink URL value will contain either a $skiptoken or a $skip query parameter. The URL also contains all the other query parameters present in the original request. Do not try to extract the $skiptoken or $skip value and use it in a different request.

... so I'm hesitant to go against that and extract the parameter and append it using the CursorPaginator.

Any help would be appreciated.

Thanks
Ben

**Comment by avenjamin** [comment]
FYI - I have since tested extracting the $skiptoken parameter using the [Spatie URL package](https://github.com/spatie/url) and that worked.

However I'd still like to know if it's possible to change the full URL in the $request?

``` PHP
protected function getNextCursor(Response $response): int|string
{
    $url = Url::fromString($response->json('@odata.nextLink'));
    return $url->getQueryParameter('$skiptoken'); // <-- might need to check both $skip and $skiptoken
}

//...

protected function applyPagination(Request $request): Request
{
    if ($this->currentResponse instanceof Response) {
        $request->query()->add('$skiptoken', $this->getNextCursor($this->currentResponse)); // <-- might need to use $skip instead $skiptoken in some cases
    }

    if (isset($this->perPageLimit)) {
        $request->query()->add('$top', $this->perPageLimit);
    }

    return $request;
}
```

**Comment by Sammyjo20** [comment]
Hey @avenjamin firstly I want to apologise for being slow to reply to your message. 

I'm going to see if there's a way I can introduce the ability to overwrite the URL on a per-request basis for situations like these. However I think you are on the right track with modifying the query parameters.

Do you have an example of how the `@odata.nextLink` value?

**Comment by avenjamin** [comment]
Hey @Sammyjo20 - no worries :)

That would be great if you could - I'm sure this won't be the only time someone will want this feature.

The original URL is:

`https://graph.microsoft.com/v1.0/users?$select=id,mail,accountEnabled,displayName,department`

And the `@odata.nextLink` URL is:

`https://graph.microsoft.com/v1.0/users?$select=id%2cmail%2caccountEnabled%2cdisplayName%2cdepartment&$skiptoken=RFNwdAIAAQA....snip....GG5AAAAA`

As you can see the URL is practically the same just with some URL escaping and the addition of the `$skiptoken`.

I'm only hesitant due to what Microsoft say in the docs which I'm reading as don't modify the URL basically and that in some instances they use `$skip` instead.

I suppose Microsoft could potentially set the `$skiptoken` to a different server hostname for load balancing. e.g. `graph-na-01.microsoft.com` but I haven't seen them do this yet:

> Important
> You should include the entire URL in the @odata.nextLink property in your request for the next page of results. Depending on the API that the query is being performed against, the @odata.nextLink URL value will contain either a $skiptoken or a $skip query parameter. The URL also contains all the other query parameters present in the original request. Do not try to extract the $skiptoken or $skip value and use it in a different request.

**Comment by Sammyjo20** [comment]
Hey @avenjamin 

Thanks for the information - I've had a look into building a new `url()` API for Saloon's requests/connectors but I think it's going to be too difficult to retrofit it into v3 for everyone. I would recommend that you add your own `setEndpoint()` method on your request, which internally sets a property. When the endpoint is a full URL it'll be preferred over the base URL defined on the connector.

```php
class YourRequest extends Request
{
     protected string $endpoint = '/default';

     protected function resolveEndpoint()
     {
         return $this->endpoint;
     }

     public function setEndpoint(string $endpoint): void
     {
         $this->endpoint = $endpoint;
     }
}


// ...

protected function applyPagination(Request $request): Request
{
    if ($this->currentResponse instanceof Response) {
        $request->setEndpoint($this->currentResponse->json('@odata.nextLink'));
    }

    // ...
}
```

**Comment by avenjamin** [comment]
Thanks @Sammyjo20 - maybe in v4 :)

I did as you suggested and it's working well so far.
I also just used the same technique for another API which has the page number as part of the URL (not a query parameter).

We can close this for now.

Cheers
Ben
