### ISSUE TITLE
Create commands not respecting config file

### ISSUE THREAD

**Issue by ClaraLeigh** [Sammyjo20/Saloon#367]
Hey 👋

It looks like the commands to create files aren't actually linked up to the config setting for integrations_path, like it implies.

I am sure it's a quick fix but I'm flat out this week working on a saloon integration so I can't open a PR for it rn.
Thought the next best thing would be to create an issue incase someone else has time to fix it up or so that other people might find this if they are wondering why its not working.

Thanks for the great package :)

**Comment by Sammyjo20** [comment]
Hey @ClaraLeigh thank you for getting in touch - and thank you for the kind words. I am in the process of reviewing a PR:

https://github.com/saloonphp/laravel-plugin/pull/56

Let me know if that will fix your problem and I will get the PR out as soon as I can!

**Comment by ClaraLeigh** [comment]
Perfection 😎

**Comment by Sammyjo20** [comment]
Hey @ClaraLeigh this has now been fixed in the latest release of the `saloonphp/laravel-plugin` library. :)

**Comment by ClaraLeigh** [comment]
Pog ty
