### ISSUE TITLE
Missing methods updates for MockResponse

### ISSUE THREAD

**Issue by brandonferens** [Sammyjo20/Saloon#389]
Currently the docs say: 

> Body Method Renamed On MockResponse
Previously, Saloon had a method getBody() on a MockResponse class. This has now been renamed to body() to be more consistent with the rest of Saloon. Additionally, the old getBodyAsString() method has been removed.

I discovered that `getHeaders()` has been updated to `headers()` and `getStatus()` has been changed to `status()`. Not sure if there are other ones as well. Just thought you'd like to know!

**Comment by Sammyjo20** [comment]
Oh thank you very much for letting me know @brandonferens! I have updated the guide 🙌

<img width="779" alt="Screenshot 2024-03-19 at 22 54 59" src="https://github.com/saloonphp/saloon/assets/29132017/1d62deb7-b5b5-4abc-97d7-8edb8e2f364a">
