### ISSUE TITLE
[proposal] Use `illuminate/http` instead of the Guzzle client

### ISSUE THREAD

**Issue by rennokki** [Sammyjo20/Saloon#4]
This package looks promising to implement API SDKs.

I was thinking about testing requests with this package - would make sense to use `illuminate/http` as it can be mocked internally without having to re-write mocks within this package.

```php
Http::fake([
    'https://forge.laravel.com/*' => Http::response(['foo' => 'bar'], 200, $headers),
]);

$request = new GetForgeServerRequest(serverId: '123456');

$response = $request->send();
$data = $response->json();
```

I might as well submit a PR to make this change, but that would leave a lot of changes (perhaps). 🤔

**Comment by Sammyjo20** [comment]
Thanks for the suggestion, but I don't want Saloon to use the Http facade as  I was going to add the same testing functionality in the `sammyjo20/saloon-laravel` package using the service container. I really like how `illuminate/http` works for testing. In fact I will aim to build it exactly the same way, but only for the Laravel package of Saloon.

**Comment by Sammyjo20** [comment]
I already have a plan in my head on how I'm going to do it. The service container is super powerful - so when you call `Saloon::fake()` it will queue requests and then I'll use a custom Guzzle handler which checks if there are any queues responses not yet fulfilled and it will return them instead.

**Comment by rennokki** [comment]
I'm going to close this issue then. I'll be happy to give feedback during the development. I'm already planning to use it for some packages at @renoki-co
