### ISSUE TITLE
Generating Documentation Files for GPT on ChatGPT

### ISSUE THREAD

**Issue by dangnhdev** [Sammyjo20/Saloon#412]
I would like to generate a PDF or JSON file for the documentation to create a GPT on ChatGPT. I am aware of the [htmlbook2pdf crawler](https://github.com/lufengd3/htmlbook2pdf), but I am looking for an easier method.

Thank you, @Sammyjo20, for this awesome library!

**Comment by Sammyjo20** [comment]
Hey @dangnhdev I'm a little confused to your request, do you want to convert Saloon's documentation into something that ChatGPT can import?

**Comment by dangnhdev** [comment]
Yes that's it 👍

**Comment by Sammyjo20** [comment]
Hey @dangnhdev I think the closest to "raw" documentation would be what you can find on the Github repository in markdown files https://github.com/Sammyjo20/saloon-docs/

**Comment by dangnhdev** [comment]
Thank you, that's enough. I didn't notice that repo existed.
