### ISSUE TITLE
async request with multi connector

### ISSUE THREAD

**Issue by mstfblci** [Sammyjo20/Saloon#414]
How exactly should I send requests asynchronously with multiple connectors?

**Comment by Sammyjo20** [comment]
Hey @mstfblci I think you may be able to do something like this, you'll need to "hack" it slightly by providing a connector to create the pool but you'll be able to use `sendAsync` on all your other connectors.

```php
$connectorA->pool()->setRequests([
     $connectorB->sendAsync($requestA),
     $connectorC->sendAsync($requestA),
     $connectorD->sendAsync($requestA),
])
```

Let me know if this doesn't work!
