### ISSUE TITLE
Asserting a request is sent by closure parameter

### ISSUE THREAD

**Issue by innocenzi** [Sammyjo20/Saloon#417]
Take the following snippet:

```php
MockClient::getGlobal()->assertSent(function (CreateDealRequest $request) {
    expect($request->body()->all())->toMatchArray([
        'title' => '[MGT] Jon Doe / foo - bar / ' . now()->addDay()->format('M d \'y'),
        'status' => DealStatus::OPEN,
    ]);
});
```

This would fail if there was a request other than `CreateDealRequest`. It would be great if `assertSent` could take the request type into account.

Open to PRing that 👍

**Comment by Sammyjo20** [comment]
Thank you for PRing this! I'm going to close this as it's now a PR.
