### ISSUE TITLE
Additional requests with the main request

### ISSUE THREAD

**Issue by mstfblci** [Sammyjo20/Saloon#437]
Hi,

Sometimes, in some APIs, I need other requests to be sent along with a request.

We can build a structure like this:

```
class AvailabilityRequest extends Request
{

    public function __construct(
        protected array $data
    )
    {
        //
    }

    public function defaultAdditionalRequests(): array
    {
        return [
            new DetailService($this->data)
        ];
    }
}
```

This will make saloonphp more useful.

**Comment by craigpotter** [comment]
Why wouldn't you just do 

```php
$myConnector->send(new RequestA($data));
$myConnector->send(new RequestB($data));
```

**Comment by Sammyjo20** [comment]
Thanks for the suggestion, but I agree with @craigpotter.

I don't think you should make additional requests inside a Saloon request. If you really need to do it, you can do the following inside of your request:

```php
use Saloon\Http\PendingRequest;

public function boot(PendingRequest $pendingRequest)
{
     $pendingRequest->getConnector()->send(new RequestB);
}
```

This above code would run before the initial request is sent.
