### ISSUE TITLE
Merged URL not valid

### ISSUE THREAD

**Issue by alexcutts** [Sammyjo20/Saloon#6]
This is a great project - exactly what I needed to standardise our API connectivity as we use a lot of integrations. I realise this is a problem with the third party API I'm using not confirming to REST specifications but want to check if anything can be done.

We use an API which has the baseUrl format `api.xxx.com/v2`
Requests are then made to endpoints in the format `model=accounts&action=load`
This leads to an actual URL of `api.xxx.com/v2?model=accounts&action=load`

Saloon constructs the URL by combining the two parts, trimming the right forward slash (if present) and then inserting a forward slash - e.g `api.xxx.com/v2/?model=accounts&action=load` - this produces a 404 error as it is now referencing a non existent directory. 

I have tried using handlers but you can't modify the base URL once set (done in `ManagesGuzzle`).

The easy solution is to just use the full URL in the Request class but this takes away some of the simplicity that this package created.

I can't think of any other way of modifying the URL before the request is made - however an option on the SaloonConnector class could allow the behaviour to be configured at runtime per connector (or alternatively, an option in the global config to add slashes on a global basis). I'm happy to submit a pull request if this is something you'd be interested in adding

**Comment by Sammyjo20** [comment]
Thanks for submitting this issue, really glad you like Saloon! This definitely sounds like a bit of a bug. Where I intended to always only have one trailing slash, it adds another. I believe a fix for this would be to not add any leading slash if it doesn’t exist already, but if one exists already - leave it in there. 

If you are happy to submit a PR for this, that would be great - if not I’ll try and add it in later today after work.

**Comment by Sammyjo20** [comment]
Actually thinking about this more - if I remove the logic that fixes trailing/leading slashes - it will become a breaking change as people will assume Saloon will fix their leading/trailing slashes (a problem that I have had before)

Maybe Saloon could introduce a new trait like “DoNotIncludeTrailingSlash” or something?

Alternatively, I can remove the logic where I add a trailing slash in the ManagesGuzzle file in the base url. This would cause people’s APIs to break unless they put a leading slash in the request.

**Comment by Sammyjo20** [comment]
Sorry for lots of comments! To be honest, I think a "DoNotIncludeTrailingSlash" would do the trick because that's the only thing that you can't control at the moment with how Saloon builds URLs. If I added that trait - you would be responsible to add the trailing slash but you could do the rest in the request endpoint.

**Comment by Sammyjo20** [comment]
This should now be fixed in v0.3.1. I've made it so if you set the endpoint in your request to be an empty string, Saloon won't append the trailing slash. Thanks for submitting this issue!
