### ISSUE TITLE
Different grant type for oauth

### ISSUE THREAD

**Issue by justageek** [Sammyjo20/Saloon#79]
Hi, we need to use 'client_credentials' to get an oauth token before every other api call we make to a third party api call.  Well we only need a new token if the previous one has expired, they have a 2 hour life.

Wondering how I can create a custom authenticator so it adds the latest token to every other request we need to make

Thanks,
Brian Smith

**Comment by Sammyjo20** [comment]
Hey Brian, are you still trying to figure this out?

**Comment by mattiusclay** [comment]
I'd love to use Saloon but it seems the 3rd party API I'm using needs grant_type to be client_credentials for the auth payload.

**Comment by justageek** [comment]
I was able to figure out a solution to my problem at this time, thanks for asking.

**Comment by Sammyjo20** [comment]
Sounds like the extra grant time might be useful! I’m open for discussion on this as I’d like people to have everything they need!

**Comment by relaypilot** [comment]
Looks like it could become possible to use `client_credentials` as the `grant_type` soon?
It's also a requirement for an API I am connecting to.
https://github.com/Sammyjo20/Saloon/issues/157

**Comment by Sammyjo20** [comment]
Hey @relaypilot!

Yes client credentials is very much on my radar - the main discussion is over at #157
