### ISSUE TITLE
License

### ISSUE THREAD

**Issue by simonhamp** [Sammyjo20/Saloon#8]
I can see you've got the LICENSE file in `.github/`, but it might be worth setting it somewhere more public.

I think if it's in the root of the project, GitHub can pick it up and pop a link to it in the sidebar

<img width="377" alt="Screenshot 2022-01-20 at 17 48 56" src="https://user-images.githubusercontent.com/31628/150393937-cfe2117d-2ad2-48bf-996e-ed1ed04a6365.png">

**Comment by Sammyjo20** [comment]
Thanks for spotting this! I've resolved this in #9
