### ISSUE TITLE
I want to record the response of all requests. What should I do

### ISSUE THREAD

**Issue by hipig** [Sammyjo20/Saloon#80]
This is really an excellent package, very useful to me
But I don't know how to record the return result of each request,
Call the `addHandle` method to achieve this?

**Comment by Sammyjo20** [comment]
I would create a response interceptor on the connector that is making all of the requests, then you can record every request...

```php
public function boot(SaloonRequest $request)
{
    $request->addResponseInterceptor(function (SaloonRequest $request, SaloonResponse $response) {
      // Store the response somewhere

      return $response;
  });
}
```

**Comment by Sammyjo20** [comment]
How did that go, @hipig ?
