### ISSUE TITLE
[v2] Drop illuminate/support requirement

### ISSUE THREAD

**Issue by Gummibeer** [Sammyjo20/Saloon#86]
As already discussed on Twitter - the `illuminate/support` package comes with some handy classes but also a ton of Laravel-specific ones. Requiring it only because of the `Arr` and/or `Str` helpers isn't really "right" and questions the "plain php" nature of that package, as there's a specific Laravel wrapper.

It will also tie this package's versioning to the Laravel lifecycle even if there hasn't been anything changed relevant to that package. As otherwise it won't be installable on the latest Laravel projects - at the same time it should support the lowest Illuminate version possible as with Illuminate and Laravel comes also PHP constraints which will possibly limit the usability of the package even further. In my experience Symfony devs also don't really like to load illuminate/support as it comes with a ton of classes absolutely not needed and will make navigating IDE more complicated.

So far I've seen the only classes used are the following. All should be "easy" to replace with a custom `Util` class or even plain PHP.

* `Illuminate\Support\Arr`
* `Illuminate\Support\Str`
* `Illuminate\Support\Collection`

https://github.com/Sammyjo20/Saloon/search?q=Illuminate

**Comment by Wulfheart** [comment]
Aren’t there also packages for each of this? So we could just include Collection?

**Comment by Gummibeer** [comment]
`Collection` is the only standalone one and is also only used for the `collect()` method. This could even be solved by a Composer `suggest` thing as it's a standalone and encapsulated method not used anywhere in the package but only a public shorthand.
https://github.com/Sammyjo20/Saloon/blob/e3f6e19daba415dd4907ada3164b77a44d3ff8f1/src/Http/SaloonResponse.php#L182-L191

And once in the `ProxyRequestNameHelper` which can be easily rewritten to a `foreach()` loop.
https://github.com/Sammyjo20/Saloon/blob/8efb063a04bd2263d26d50790ebae801bb864d22/src/Helpers/ProxyRequestNameHelper.php#L21-L37

**Comment by Jimlah** [comment]
@Gummibeer can you assign it to me. I will love to work on it.

**Comment by Gummibeer** [comment]
@Sammyjo20 will have to assign it - but I won't work on it in that cas. So go ahead! :)

**Comment by Sammyjo20** [comment]
Will be adding these changes to v2 👍
