### ISSUE TITLE
[v2] Add QueryKeyAuthenticator

### ISSUE THREAD

**Issue by Gummibeer** [Sammyjo20/Saloon#98]
Some APIs use a query param based Key authentication. For sure that's possible with a `defaultQuery()` method but somehow feels wrong. So how about a `QUeryAuthenticator` or similar named class with a signature like `new QueryAuth(string $name, string $value)`. 🤔

**Comment by Sammyjo20** [comment]
Ooh yeah that could be good! So it just adds a query parameter with the key and value?

**Comment by Gummibeer** [comment]
Exactly. Wasn't sure about naming but yeah, like `?key=abc123`

**Comment by Sammyjo20** [comment]
I can definitely add that in - but I do think defaultQuery on the connector is a good approach too, you would just need to accept the API key through the constructor of the connector.

**Comment by Gummibeer** [comment]
Yeah, doing it right now that way. But The authenticator feels better. And one question regarding priority.
If I use `defaultQuery()` to define `key=1`, the query authenticator with `key=2` and in the request itself also `defaultQuery()` with `key=3` - which one would be used? My hope would be that the authenticator has priority over both `defaultQuery()` methods - as it explicitly calls `addQuery()`. 🤔

**Comment by Sammyjo20** [comment]
I think that defaultQuery will take priority over the authenticator unfortunately. This is something that has been looked over a lot in v2 and the authenticator is basically the last thing in v2. Apologies

<img width="1173" alt="Screen Shot 2022-11-06 at 18 49 34" src="https://user-images.githubusercontent.com/29132017/200189385-31e2f82b-3b82-446d-bc7c-e9c5bbb45925.png">

**Comment by Gummibeer** [comment]
Okay, so right now the change would be (some way) even worse. 😅
But good to know and I think that in V2 an authenticator like that would make sense.

**Comment by Sammyjo20** [comment]
This has now been added to the v2 branch!
